version: "3.8"

services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    restart: "always"
    volumes:
      - "./web/:/gym_tracker"
    command: "go run ."
    env_file:
      - example.env
    depends_on:
      - db
 
  db:
    restart: always
    image: postgres:latest
    env_file: ./example.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - local_postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
  
volumes:
  local_postgres_data: {}
