version: "3.8"

services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    restart: "always"
    volumes:
      - "./web/:/gym_tracker"
    command: "go run ."
